### ISSUE TITLE
Plugin don`t worked in Android lib modules

### ISSUE THREAD

**Issue by Fantastic12** [LikeTheSalad/android-string-reference#7]
Don`t worked in multi-module architecture)

**Comment by LikeTheSalad** [comment]
Hi @Fantastic12, it's not completely clear to me what's your use case, however, if what you're trying to do is to resolve templates from a subproject dependency, then you can do so by setting the following flag to true:

```
stringXmlReference {
    useDependenciesRes = true
}
```

You can find more info on configurable options here: https://github.com/LikeTheSalad/android-string-reference#3--configurable-options

I hope it helps.

**Comment by Fantastic12** [comment]
For example, I have 2 modules.
The first is the app module which has strings with $ {app_name}. The second utils module is android lib, let's say it also has strings with $ {app_name}. The problem is that I have code in the utils module that uses these strings, and this plugin generates strings only in the app module, respectively, the code that depends on these strings in the utils module breaks down, since there are no such strings within this module, because they were generated in app

**Comment by LikeTheSalad** [comment]
I see, I think it's easy to solve, you should add in your utils module a string named "app_name" with some dummy text, for it to compile as an independent module, but no worries, because by the time you compile the app, the value "app_name" from the app will override the value "app_name" from the utils module, so in the end your generated strings will have the app's "app_name".

Btw, you should also set `useDependenciesRes = true`, as I mentioned before, in your app's build.gradle so that your utils module's templates get resolved as part of the app's compilation.

Please let me know if any issues.

**Comment by Fantastic12** [comment]
Cool, thanks
