### ISSUE TITLE
String plurals support

### ISSUE THREAD

**Issue by dantol1** [LikeTheSalad/android-string-reference#9]
Hi, I didn't see any reference for this in the README, can I use this plugin with string plurals? and if so should I use the template_ prefix on the string key, the quantity key or both?

**Comment by LikeTheSalad** [comment]
Hi @dantol1 - Since plurals isn't a string itself but rather a handy way to choose the right string at runtime depending on a quantity provided, then this plugin doesn't cover it as such, but you can still use the outcome of this plugin in a plural.

For example, by having the following template, `template_app_welcome`, set up:
```
<resources>
    <string name="app_name">Playground2</string>
    <string name="template_app_welcome">Welcome to ${app_name}</string>
</resources>
```
You can tell that this plugin will generate a string named `app_welcome` at some point, which means that you can use it wherever you need, such as in a plural, e.g:

```
<resources>
    <plurals name="some_plural">
        <item quantity="one">Singular</item>
        <item quantity="other">@string/app_welcome</item>
    </plurals>
</resources>
```

I hope it helps!
Cesar

**Comment by dantol1** [comment]
works great, thanks a lot!

**Comment by LikeTheSalad** [comment]
Awesome! glad to hear it worked out well for you 👍
